### ISSUE TITLE
`npm run test:browser` locally starts sauce labs browsers

### ISSUE THREAD

**Issue by mightyiam** [eventualbuddha/keysim.js#21]

**Comment by mightyiam** [comment]
[Zuul](https://www.npmjs.com/package/zuul) works a bit better and is gaining popularity and is easier to configure.

**Comment by eventualbuddha** [comment]
I'd be fine using Zuul. I don't really have time to make the change myself, but I'd merge a PR to do it.

**Comment by eventualbuddha** [comment]
I don't remember whether it worked this way at the time, but `npm run test:browser` now launches a local browser with karma. Closing since it seems to work as expected now.
