### ISSUE TITLE
element.value not updated

### ISSUE THREAD

**Issue by colmsjo** [eventualbuddha/keysim.js#22]
I can't see that the value in the DOM is changed. what am I doing wrong here:

```
    var out = document.getElementById('out');
    var keyboard = Keysim.Keyboard.US_ENGLISH;
    keyboard.dispatchEventsForInput('hello!', out);
    setTimeout(function() {console.log('out.value:' + out.value)}, 1000);
```

I can see that the events are fired though.

Any help is greatly appreciated!

**Comment by eventualbuddha** [comment]
@colmsjo your confusion is understandable. I tried to address it in the [README](https://github.com/eventualbuddha/keysim.js#usage), but maybe it wasn't clear or obvious enough? Here's the relevant section:

> Note that none of the methods provided by keysim will trigger the browser's default behavior, such as inserting text or moving the cursor. It only allows you to test your event handling code by sending the correct DOM events.

Thoughts on how to improve it for the next person?

**Comment by swedenultimate** [comment]
I figured this after scratching my head (and googling) a lot. I think it was this guide that made me realize how synthetic events actually works: http://dojotoolkit.org/reference-guide/1.7/util/dohrobot.html

**Comment by colmsjo** [comment]
My comment above (was logged in with wrong account)...

**Comment by stevenvachon** [comment]
I think that "none of the methods provided by keysim will trigger the browser's default behavior" should be bolded.
