### ISSUE TITLE
charCode is 0 for KeyPresses on PhantomJS

### ISSUE THREAD

**Issue by jameslnewell** [eventualbuddha/keysim.js#23]
Happens somewhere inside .createEventFromKeystroke()

**Comment by eventualbuddha** [comment]
Thanks for the report, @jameslnewell. The easiest way for me to figure out what's going on and fix it is to have a reproducible test case, ideally on something like [JSBin](http://jsbin.com/) or as an HTML file with the appropriate JavaScript inline. Would you mind putting something like that together? Thanks!

**Comment by eventualbuddha** [comment]
@jameslnewell closing until I can get a reproducible test case. I'm happy to look into it once I have that to work with.
