### ISSUE TITLE
dispatchEventsForInput isn't providing all event properties

### ISSUE THREAD

**Issue by kof** [eventualbuddha/keysim.js#39]
In particular I am listening to onKeyDown and accessing event.key event property, which is defined by the browser when typing. 

Like this: `keyboard.dispatchEventsForInput('hello!', textarea)`

**Comment by stevenvachon** [comment]
Yes, `key` and `code` are missing.

**Comment by stevenvachon** [comment]
@eventualbuddha thoughts on this? I'm planning to create a package that depends on this to populate form fields.

**Comment by eventualbuddha** [comment]
I don’t have a lot of time to do this right now, but can review a PR.

**Comment by stevenvachon** [comment]
I can do it, but do you have any information on the differences between `code` and `keyCode` that can save me time?

**Comment by eventualbuddha** [comment]
Not really. I knew more about it when I was actively developing this library, but it’s been mostly forgotten.
