### ISSUE TITLE
keypress not dispatched for 'enter' action

### ISSUE THREAD

**Issue by stevenvachon** [eventualbuddha/keysim.js#52]
...because it has [no char code](https://github.com/eventualbuddha/keysim.js/blob/master/src/keysim.js#L258).

```js
const element = document.createElement('input');

element.addEventListener('keypress', event => console.log(event.keyCode));
document.body.appendChild(element);
```
```js
Keysim.Keyboard.US_ENGLISH.dispatchEventsForAction('enter', element);
```
```js
const keystroke = new Keysim.Keystroke(0, 13);
Keysim.Keyboard.US_ENGLISH.dispatchEventsForKeystroke(keystroke, element);
```

It probably should have a char code, right? Safari has the same value as `keyCode`.

Also, Firefox dispatches 'keypress' events for Backspace, Tab and Escape keys while Chrome does not.

**Comment by eventualbuddha** [comment]
Seems like it should have a `charCode`. Want to make a PR?

**Comment by stevenvachon** [comment]
My guess is to avoid ever giving `charCode` a [`null` value](https://github.com/eventualbuddha/keysim.js/blob/master/src/keysim.js#L101). Sound right?

**Comment by eventualbuddha** [comment]
Not sure. I think this could be fixed by adding an entry to `US_ENGLISH_CHARCODE_KEYCODE_MAP`.

**Comment by stevenvachon** [comment]
I think that if a keystroke is added to that map, we lose the modifier keys.

**Comment by eventualbuddha** [comment]
There should be tests to verify that change.

**Comment by stevenvachon** [comment]
Firefox assigns a `charCode` value of 0 instead of null when there is no such code.
