### ISSUE TITLE
Could you please provide working full html example?

### ISSUE THREAD

**Issue by Kosteg** [eventualbuddha/keysim.js#58]
Hi! Could you please provide working full html example or url to working example?

I don't develop apps and I don't know how to build project with yarn/npm/webpack/babel/dependencies etc...

I would like to inject keysim into existing webpage and use it to autofill forms. So working example would really help.

**Comment by eventualbuddha** [comment]
I updated the README with a link to a [jsbin](http://jsbin.com/tujidubile/edit?html,output).

**Comment by Kosteg** [comment]
The example pushes events to the log, that's nice, thank you very much. But it doesn't actually fill any input field. Could you please give the working example – how to programmatically fill some input field?

**Comment by eventualbuddha** [comment]
Also from the README:

> Note that none of the methods provided by keysim will trigger the browser's default behavior, such as inserting text or moving the cursor. It only allows you to test your event handling code by sending the correct DOM events.

This has been a point of confusion for this library. Can you suggest a way to make that clearer?
