### ISSUE TITLE
Export `default` for Webpack

### ISSUE THREAD

**Issue by stevenvachon** [eventualbuddha/keysim.js#62]
```js
module.exports.default = ...;
```

**Comment by eventualbuddha** [comment]
What exactly would you want the default export to be?

**Comment by stevenvachon** [comment]
The same as `window.Keysim`, I would think.

**Comment by eventualbuddha** [comment]
You can already use it in a commonjs context, though I haven't tried it with webpack specifically. You can just e.g. `import { Keyboard } from 'keysim';`. If you have any specific issues feel free to comment here or open a new issue.

**Comment by stevenvachon** [comment]
That syntax is gross and this issue was created to avoid having to use it.

**Comment by eventualbuddha** [comment]
Well, I personally disagree with the syntax being gross, but I can understand how one might think so. I'd rather not make the library less semantically correct just to improve aesthetics a bit.

**Comment by stevenvachon** [comment]
Hmm, now that I look at the source code again, your point is valid.
