### ISSUE TITLE
Run in IE7&8

### ISSUE THREAD

**Issue by mightyiam** [eventualbuddha/keysim.js#7]
Hi, Brian. Thanks for the advise in WYMeditor and for this awesome module.

In WYMeditor, we target IE7&8, which can't seem to be able to run Keysim.

The issue I ran into was `Object.prototype.defineProperty`, if I remember correctly.

Is there a chance that it would be very simple to alter Keysim to run in IE7&8 succesfully?

**Comment by eventualbuddha** [comment]
Though I haven't actually tested it in IE7 & 8, I believe it should now work in v1.1.2.

**Comment by mightyiam** [comment]
Thank you. I will debug on IE7&8 probably around Sunday.

**Comment by mightyiam** [comment]
@eventualbuddha IE8 seems to crash on [this jsdom literal object property getter](https://github.com/tmpvar/jsdom/blob/2ff5747488ad4b518fcef97a026c82eab42a0a14/lib/jsdom/browser/Window.js#L143).

[MDN claims](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) these getters are only since IE9.

**Comment by mightyiam** [comment]
Perhaps we should use real DOM in browsers and jsdom only in node?

**Comment by mightyiam** [comment]
I'm trying to prevent that property `: get` code from executing in browsers, by not running `require('jsdom')` in browser (only in node).

But it seems that this isn't enough, because even if the code doesn't run, it is read by the browser and the error is invoked.

How can I get this code to entirely not be present in browsers? It would have to not get browserified, at all.

Browserify has the [`b.exclude()`](https://github.com/substack/node-browserify#bexcludefile) API. I wonder if we can use that through Karma.

I think I got it. Submitting PR.

**Comment by mightyiam** [comment]
#8 seems like a step forward for IE7&8.

Next broken thing seems to be `Array.prototype.forEach`.

Would you prefer a PR that converts to an old `for` loop, or rely on shimming in tests?

**Comment by mightyiam** [comment]
In any case, I suggest reopening this.

**Comment by eventualbuddha** [comment]
I played around with this for a while and was not able to get it working in an automated way with Karma. I did run it in Sauce Labs with a manual session in both IE7 and IE8 and this jsbin worked: http://jsbin.com/hozuvaheqe/1/

If you have time to figure out what worked in that jsbin and make a PR out of it I'd be happy to merge it, but I've reached the end of the time I can spend on this.

**Comment by mightyiam** [comment]
Pull requests #10, #12, #13 and #14 seem to be steps towards this end.

**Comment by mightyiam** [comment]
Add in #16 to the list.

**Comment by mightyiam** [comment]
Add #17, as well.

**Comment by mightyiam** [comment]
#19 may help.
